language: android
sudo: false
android:
  components:
    - tools
    - platform-tools
    - tools
    - build-tools-25.0.2

    # The SDK version used to compile project
    - android-25
    #- android-21

    # Additional components
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    # Specify at least one system image,
    # if we need to run emulator(s) during tests
    #- sys-img-armeabi-v7a-android-21
    #- sys-img-armeabi-v7a-android-25

  licenses:
    - android-sdk-preview-license-52d11cd2 # Solver for ConstraintLayout
    - android-sdk-license-5be876d5 # Android SDK Build-Tools
    - android-sdk-license-c81a61d9 # Package Google Repository

jdk: oraclejdk8
